name: Send to Discord Webhook

on:
  schedule:
    - cron: '* * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  send-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read file, extract first word, and update file
        id: file_operations
        run: |
          # Set the file path
          FILE_PATH="Hamiltion.txt"

          # Ensure the file is not empty before processing
          if [[ ! -s "$FILE_PATH" ]]; then
            echo "File is empty. Exiting."
            exit 0
          fi
          
          # Read the first word and remove it from the file
          FIRST_WORD=$(head -n 1 $FILE_PATH | awk '{print $1}')
          
          # Send first word to Discord webhook
          echo "First word: $FIRST_WORD"
          
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"$FIRST_WORD\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
          
          # Remove the first word from the file
          sed -i '1s/^[^ ]* //' $FILE_PATH

      - name: Commit and push changes
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Check if the file has changed
          if [[ -n $(git status --porcelain) ]]; then
            git add Hamiltion.txt
            git commit -m "Removed first word from Hamiltion.txt"
            git push
          else
            echo "No changes to commit."
          fi
